[versions]
kotlin = "1.6.10"
dagger = "2.43.2"

[libraries]
sqlite = { module = "org.xerial:sqlite-jdbc", version = "3.36.0.3" }
junit = { module = "org.junit.jupiter:junit-jupiter-engine", version = "5.8.1" }
coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version = "1.6.0" }
testCoroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version = "1.6.1" }
truth = { module = "com.google.truth:truth", version = "1.1.3" }
daggerCompiler = { module = "com.google.dagger:dagger-compiler", version.ref = "dagger" }
dagger = { module = "com.google.dagger:dagger", version.ref = "dagger" }


[plugins]
compose = { id = "org.jetbrains.compose", version = "1.1.1" }